repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.4  # Use the latest stable version
    hooks:
      # linter
      - id: ruff
        args: [check]  # Customize linting rules as needed
      # formatter
      - id: ruff
        args: [format]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
