# Generated by Django 5.1.1 on 2024-09-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="text",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
