# Generated by Django 5.1.1 on 2024-09-07 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_text_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="text",
            name="file_source",
        ),
    ]
