# Generated by Django 5.1.1 on 2024-09-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_remove_text_file_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="text",
            name="file_source",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
